create database trabalhoFinal;
use trabalhoFinal;

create table filme (
	id serial,
	titulo varchar(100) not null,
	duracao int not null,
	genero varchar(45) not null,
	sinopse varchar(500) not null,
	elenco varchar(300) not null,
	personagens varchar(300) not null,
	paisOrigem varchar(45) not null,
	idioma varchar(45) not null,
	escritores varchar(200) not null,
	direcao varchar(100) not null,
	anoLancamento int not null,
	linkimagem varchar(200) not null,
	linkimdb varchar(100) not null,
	linkassistir varchar(100) not null,
	contadorfavoritos int not null,
	primary key (id));

	create table serie (
		id serial,
		titulo varchar(100) not null,
		direcao varchar(200) not null,
		elenco varchar(300) not null,
		personagens varchar(300) not null,
		sinopse varchar(500) not null,
		anoLancamento int not null,
		tempoEpisodio int not null,
		qntTemporadas int not null,
		episodiosTemporada int not null,
		ondeAssistir varchar(45) not null,
		paisOrigem varchar(45) not null,
		idioma varchar(45) not null,
		escritores varchar(200) not null,
		linkimagem varchar(200) not null,
		linkimdb varchar(100) not null,
		linkassistir varchar(100) not null,
		contadorfavoritos int not null,
		primary key (id));

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (6, 'Léon: The Professional', 110, 'Ação', 'Mathilda, uma doce e ignorada garota de 12 anos passa a viver com um matador de aluguel após sua família ser assassinada.', 'Jean Reano, Natalie Portman, Gary Oldman', 'Leon, Mathilda, Stansfield', 'Estados Unidos', 'Inglês', 'Luc Besson', 'Luc Besson', 1994, 'https://wallpapercave.com/wp/wp2167378.jpg', 'https://www.imdb.com/title/tt0110413/?ref_=rt_li_tt', 'https://www.netflix.com/search?q=leon&jbv=7880857', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (9, 'De Volta ao Jogo', 101, 'Ação', 'Um ex-matador sai da aposentadoria para rastrear os gangsters que mataram seu cachorro e levaram tudo dele', 'Keanu Reeves, Michael Nyqvist, Alfie Allen', 'John Wick, Viggo Tarasov, Iosef Tarasov', 'Estados Unidos', 'Inglês', 'Derek Kolstad', 'Chad Stahelski, David Leitch', 2014, 'https://images2.alphacoders.com/550/550911.jpg', 'https://www.imdb.com/title/tt2911666/?ref_=fn_al_tt_1', 'https://www.primevideo.com/detail/0PZ1Q2RV0FRLPFEHAE4WGBICPK/ref=atv_sr_def_c_unkc__1_1_1?sr=1-1&pageTypeIdSource=ASIN&pageTypeId=B08BXCDDZ7&qid=1600194776', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (3, 'Pulp Fiction', 150, 'Aventura', 'Os caminhos de vários criminosos se cruzam nestas três histórias de Quentin Tarantino. Um pistoleiro se apaixona pela mulher de seu chefe, um boxeador não se sai bem em uma luta e um casal tenta executar um plano de roubo que foge do controle.', 'Uma Thurman, John Travolta, Samuel L. Jackson', 'Vicent Vega, Mia Wallace, Marsellus Wallace', 'Estados Unidos', 'Inglês', 'Quentin Tarantino', 'Quentin Tarantino', 1994, 'https://i0.wp.com/braincharm.com/wp-content/uploads/2017/11/Pulp-Fiction-Gradient.jpg?fit=1920%2C1080&ssl=1', 'https://www.imdb.com/title/tt0110912/', 'https://www.netflix.com/va-en/title/880640', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (5, 'A Princesa Prometida', 98, 'Aventura', 'Enquanto doente, um avô lê para seu neto uma história épica com muita aventura, diversão, sátiras e com uma linda história de amor', 'Cary Elwes, Mandy Patinkin, Robin Wright, Wallace Shawn', 'Westley, Inigo Montoya, Vizzini, Fezzik, The Princess Bride', 'Estados Unidos', 'Inglês', 'William Goldman', 'Rob Reiner', 1987, 'https://wallpapercave.com/wp/wp4138198.jpg', 'https://www.imdb.com/title/tt0093779/', 'https://www.primevideo.com/detail/0K1WVGHO9SD7J2PSKNGYF2JQQ0/ref=atv_sr_def_c_unkc__1_1_1?sr=1-1&pageTypeIdSource=ASIN&pageTypeId=B0875GZLCH&qid=1600096907', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (2, 'Feitiço do Tempo', 101, 'Comédia', 'Um jornalista e homem do tempo enviado para cobrir o Dia da Marmota, se encontra inexplicavelmente revivendo esse mesmo dia eternamente.', 'Bill Murray, Andie MacDowell', 'Phil, Rita', 'Estados Unidos', 'Inglês', 'Danny Rubin, Harold Ramis', 'Harold Ramis', 1993, 'https://wallpapers.moviemania.io/desktop/movie/137/6a0cf9/groundhog-day-desktop-wallpaper.jpg?w=2552&h=1442', 'https://www.imdb.com/title/tt0107048/', '', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (8, 'A Proposta', 108, 'Comédia', 'Um chefe mandão que sua jovem assistente se case com ela para que ela possa manter seu visto nos Estados Unidos e não ser deportada para o Canadá.', 'Sandra Bullock, Ryan Reynolds, Mary Steenburgen', 'Margaret Tate, Andrew Paxton, Grace Paxton', 'Estados Unidos', 'Inglês', 'Peter Chiarelli', 'Anne Fletcher', 2009, 'https://images6.alphacoders.com/824/824674.jpg', 'https://www.imdb.com/title/tt1041829/?ref_=fn_al_tt_1', 'https://www.telecineplay.com.br/filme/A_Proposta_7147', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (7, 'O Senhor dos Anéis: A Sociedade do Anel', 178, 'Fantasia', 'Um grupo de hobbits, elfos, anões e humanos entram em uma jornada a fim de destruir o Um Anel e salvar a Terra Média', 'Sean Astin,  Sala baker, Sean Bean, Cate Blanchett, Orlando Bloom', 'Sam, Sauron, Boromir, Galadriel, Legolas', 'Estados Unidos/Nova Zelândia', 'Inglês', 'J. R. R. Tolkien', 'Peter Jackson', 2001, 'https://images7.alphacoders.com/434/thumb-1920-434813.jpg', 'https://www.imdb.com/title/tt0120737/?ref_=nv_sr_srsg_0', 'https://www.netflix.com/title/60004480', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (10, 'Harry Potter e a Câmara Secreta ', 161, 'Fantasia', 'Um mito antigo parece ser corroborado quando uma misteriosa presença começa a perseguir os corredores da escola mágica, deixando suas vítimas petrificadas.', 'Daniel Radcliffe, Emma Watson, Richard Harris', 'Harry Potter, Hermione, Albus Dumbledore', 'Reino Unido/Estados Unidos', 'Inglês', 'J.K. Rowling, Steve Kloves', 'Chris Columbus', 2002, 'https://images7.alphacoders.com/506/506800.jpg', 'https://www.imdb.com/title/tt0295297/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/60024925', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (11, 'Perdido em Marte', 144, 'Ficção Científica', 'Um astronauta fica atrapado em Marte quando seu team pensa que ele morreu, ele deberá fazer o que possa para tentar enviar uma senal ate a Terra.', 'Matt Damon, Jessica Chastain, Kristen Wiig', 'Mark Watney, Melissa Lewis, Annie Montrose', 'Reino Unido/Estados Unidos', 'Inglês', 'Drew Goddard, Andy Weir', 'Ridley Scott', 2015, 'https://images.alphacoders.com/533/533958.jpg', 'https://www.imdb.com/title/tt3659388/?ref_=fn_al_tt_1', 'https://www.telecineplay.com.br/filme/Perdido_Em_Marte_6059', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (12, 'Matrix', 136, 'Ficção Científica', 'Um hacker aprende com os misteriosos rebeldes sobre a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.', ' Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'Neo, Morpheus, Trinity', 'Estados Unidos', 'Inglês', 'Lilly Wachowski, Lana Wachowski', 'Lana Wachowski, Lilly Wachowski', 1999, 'https://images.alphacoders.com/489/489652.jpg', 'https://www.imdb.com/title/tt0133093/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/60027695', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (1, 'La la Land', 129, 'Romance', 'Um pianista é uma frustrada actora se apaixonam enquanto tentam trabalhar por seus futuros.', 'Ryan Gosling, Emma Stone', 'Sebastian, Mia', 'Filipinas', 'Inglês', 'Damien Chazelle', 'Damien Chazelle', 2016, 'https://pbtpullzone-mdvouxes9csrfg.netdna-ssl.com/wp-content/uploads/2017/06/la-la-land-cover-2250.jpg', 'https://www.imdb.com/title/tt3783958/', 'https://www.netflix.com/br-en/title/80095365', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (13, 'Como Eu Era Antes de Você', 106, 'Romance', 'Uma garota forma um vínculo improvável com um homem recentemente paralisado que ela está cuidando.', 'Emilia Clarke, Sam Claflin, Janet McTeer', 'Lou Clark, Will Traynor, Camilla Traynor', 'Reino Unido/Estados Unidos', 'Inglês', 'Jojo Moyes', 'Thea Sharrock', 2016, 'https://images8.alphacoders.com/723/723808.jpg', 'https://www.imdb.com/title/tt2674426/?ref_=fn_tt_tt_1', 'https://www.netflix.com/title/80043744', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (14, 'It: A Coisa', 135, 'Terror', 'Um grupo de garotos maltratados se une para destruir um monstro que se disfarça de palhaço e ataca as crianças de sua pequena cidade.', 'Bill Skarsgard, Jaeden Martell, Finn Wolfhard', 'Pennywise, Bill Denbrough, Richie Tozier', 'Canada/Estados Unidos', 'Inglês', ' Chase Palmer, Cary Joji Fukunaga', 'Andy Muschietti', 2017, 'https://images3.alphacoders.com/817/817146.jpg', 'https://www.imdb.com/title/tt1396484/?ref_=fn_al_tt_1', 'https://www.telecineplay.com.br/filme/It_A_Coisa_15456', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (15, 'Doutor Sono', 152, 'Terror', 'Anos após os eventos de O Iluminado, Dan Torrence, agora adulto, conhece uma jovem com poderes semelhantes aos seus e tenta protegê-la de um culto que ataca crianças com poderes de permanecer imortais.', 'Ewan McGregor, Rebecca Ferguson, Kyliegh Curran', 'Dan Torrance, Rose the Hat, Abra Stone', 'Reino Unido/Estados Unidos', 'Inglês', 'Mike Flanagan, Stephen King', 'Mike Flanagan', 2019, 'https://images7.alphacoders.com/905/905061.jpg', 'https://www.imdb.com/title/tt5606664/?ref_=adv_li_tt', '', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (4, 'I See You', 98, 'Thriller', 'Estranhos acontecimentos começam a ocorrer em uma cidade pequena, em que um detetive e su familia investigam o desaperecimento de um garotinho.', 'Helen Hunt, Jont Tenney, Judah Lewis, Owen Teague, Libe Barer', 'Jackie Harper, Greg Harper, Connor Harper, Alec, Mindy', 'Estados Unidos', 'Inglês', 'Devon Graye', 'Adam Randall', 2019, 'https://cdn3.movieweb.com/i/article/TgbssiwJuHcdmChoXrOAJncsClH1YA/1200:100/I-See-You-Trailer-2019.jpg', 'https://www.imdb.com/title/tt6079516/?ref_=ttmi_tt', '', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (16, 'Coringa', 122, 'Thriller', 'Um comediante falido enlouquece e se torna um assassino psicopata.', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz', 'Arthur Fleck, Murray Franklin, Sophie Dumond', 'Estados Unidos', 'Inglês', 'Todd Phillips, Scott Silver', 'Todd Phillips', 2019, 'https://images2.alphacoders.com/101/1013809.jpg', 'https://www.imdb.com/title/tt7286456/?ref_=adv_li_tt', '', 0);

insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (17, 'Aconteceu Naquela Noite', 105, 'Romance', 'Uma garota rica mimada que foge de sua familia é ajudada por um reporter que precisa de uma história para entregar ao jornal em que trabalha.', 'Clark Gable, Claudette Colbert Walter Conolly', 'Peter Warne, Ellie Andrews, Alexander Andrews', 'Estados Unidos', 'Inglês', 'Robert Riskin, Samuel Hopkins', 'Frank Capra', 1934, 'https://static01.nyt.com/images/2017/01/27/watching/it-happened-one-night-watching-recommendation/it-happened-one-night-watching-recommendation-videoSixteenByNineJumbo1600.jpg', 'https://www.imdb.com/title/tt0025316/', '', 0);
insert into filme (id, titulo, duracao, genero, sinopse, elenco, personagens, paisOrigem, idioma, escritores, direcao, anoLancamento, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (18, 'Les Diaboliques', 117, 'Terror', 'A esposa e a amante do diretor de uma escola planejam matá-lo acreditando possuírem o alibi perfeito.', 'Simone Signoret, Véra Clouzot, Paul Merisse', 'Nicole Horner, Christina Delasalle, Michel Delasalle', 'França', 'Francês/Inglês', 'Pierre Boileau', 'Henri-George Clouzot', 1955, 'https://image.tmdb.org/t/p/original/77WBVUYEiMJO4oB8dNvUJMS5dRR.jpg', 'https://www.imdb.com/title/tt0046911/?ref_=ttls_li_tt', '', 0);

insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (1, 'Friends', 'David Crane, Marta Kauffman', 'Matthew Perry, Jennifer Aniston', 'Chandler, Rachel', 'Relata a vida pessoal de seis amigos em seus 30s na cidade de Manhattan', 1994, 22, 10, 24, 'Netflix', 'Estados Unidos', 'Inglês', 'David Crane, Marta Kauffman', 'http://getwallpapers.com/wallpaper/full/8/5/a/1017901-download-friends-tv-show-wallpapers-1920x1080.jpg', 'https://www.imdb.com/title/tt0108778/', 'https://www.netflix.com/title/70153404', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (2, 'The Big Bang Theory', 'Chuck Lorre, Bill Prady', 'Johnny Galecki, Jim Parsons, Kaley Cuoco', 'Leonard Hofstadter, Sheldon Cooper, Penny', 'Uma mulher se muda para um apartamento do outro lado do corredor perto de dois físicos brilhantes, mas socialmente desajeitados, e lhes mostra quão pouco sabem sobre a vida fora do laboratório.', 2007, 25, 12, 24, 'Globoplay', 'Estados Unidos', 'Inglês', 'Chuck Lorre, Bill Prady', 'https://images8.alphacoders.com/509/509440.jpg', 'https://www.imdb.com/title/tt0898266/?ref_=nv_sr_srsg_0', 'https://globoplay.globo.com/the-big-bang-theory/t/fhmwKtSNxG/?gclid=EAIaIQobChMIk4DI4vfr6wIVigyRCh1ZHw3dEAAYASAAEgJiYPD_BwE', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (3, 'Brooklyn Nine-Nine', 'Dan Goor, Michael Schur', 'Andy Samberg, Stephanie Beatriz, Terry Crews', 'Jake Peralta, Rosa Diaz, Terry Jeffords', 'Jake Peralta, um detetive imaturo de Nova York, entra em conflito com seu novo comandante, o sério e severo Capitão Ray Holt.', 2013, 25, 7, 22, 'Netflix', 'Estados Unidos', 'Inglês', 'Dan Goor, Michael Schur', 'https://images5.alphacoders.com/566/566189.jpg', 'https://www.imdb.com/title/tt2467372/?ref_=nv_sr_srsg_0', 'https://www.netflix.com/title/70281562', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (4, 'Greys Anatomy', 'Shonda Rhimes', 'Ellen Pompeo, Chandra Wilson, James Pickens Jr', 'Meredith Grey, Miranda Bailey, Richard Webber', 'Drama centrado na vida pessoal e profissional de cinco estagiários e seus supervisores.', 2005, 45, 16, 24, 'Netflix', 'Estados Unidos', 'Inglês', 'Shonda Rhimes', 'https://images7.alphacoders.com/853/853241.jpg', 'https://www.imdb.com/title/tt0413573/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/70140391', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (5, 'Black Mirror', 'Charlie Brooker', 'Daniel Lapaine, Hannah John-Kamen, Charles Babalola', 'Dawson, Selma Telse, Tusk', 'Uma série de antologias explora um mundo de alta tecnologia, onde as maiores inovações da humanidade e os instintos mais sombrios colidem.', 2011, 60, 5, 5, 'Netflix', 'Reino Unido', 'Inglês', 'Charlie Brooker', 'https://images7.alphacoders.com/902/902698.jpg', 'https://www.imdb.com/title/tt2085059/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/70264888', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (6, 'Community', 'Dan Harmon', 'Joel McHale, Danny Pudi, Donald Glover', 'Jeff Winger, Abed Nadir, Troy Barnes', 'Um advogado é obrigado a entrar na universidade depois de ser suspendido de seu trabalho.', 2009, 25, 6, 20, 'Netflix', 'Estados Unidos', 'Inglês', 'Dan Harmon', 'https://images8.alphacoders.com/807/807815.jpg', 'https://www.imdb.com/title/tt1439629/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/70155589', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (7, 'The Office', 'Greg Daniels, Ricky Gervais, Stephen Merchant', 'Steve Carell, Jenna Fischer, John Krasinski', 'Michael Scott, Pam Beesly, Jim Halpert', 'Um mockumentary sobre um grupo de trabalhadores de escritório, onde o dia de trabalho consiste em conflitos de ego e comportamento inadequado.', 2005, 25, 9, 22, 'Globoplay', 'Estados Unidos', 'Inglês', 'Greg Daniels, Ricky Gervais, Stephen Merchant', 'https://images6.alphacoders.com/420/420127.jpg', 'https://www.imdb.com/title/tt0386676/?ref_=fn_al_tt_1', 'https://globoplay.globo.com/the-office/t/R1wvLRKpwn/?gclid=EAIaIQobChMIsceLhf7r6wIVChKRCh01uwK3EAAYASAAEgJqSPD_BwE', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (8, 'Suits', 'Aaron Korsh', 'Gabriel Macht, Patrick J Adams, Meghan Markle', 'Harvey Specter, Mike Ross, Rachel Zane', 'Na fuga de um negócio de drogas que acabou mal, Mike Ross, um brilhante abandono da faculdade, encontra um trabalho trabalhando com Harvey Specter, um dos melhores advogados de Nova York.', 2011, 45, 9, 16, 'Netflix', 'Estados Unidos', 'Inglês', 'Aaron Korsh', 'https://images7.alphacoders.com/691/691265.jpg', 'https://www.imdb.com/title/tt1632701/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/70195800', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (9, 'How I Met Your Mother', 'Carter Bays, Craig Thomas', 'Josh Radnor, Jason Segel, Cobie Smulders', 'Ted Mosby, Marshall Eriksen, Robin Scherbatsky', 'Um pai relata a seus filhos,a jornada que ele e seus quatro melhores amigos levaram até ele conhecer sua mãe.', 2005, 25, 9, 24, 'Netflix', 'Estados Unidos', 'Inglês', 'Carter Bays, Craig Thomas', 'https://images8.alphacoders.com/485/485340.jpg', 'https://www.imdb.com/title/tt0460649/?ref_=nv_sr_srsg_0', 'https://www.netflix.com/title/70143824', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (10, 'Breaking Bad', 'Vince Gilligan', 'Bryan Cranston, Aaron Paul, Anna Gunn', 'Walter White, Jesse Pinkman, Skyler White', 'Um professor de química diagnosticado com câncer de pulmão se transforma em fabricante e vendedor de metanfetamina, a fim de garantir o futuro da sua família.', 2008, 47, 5, 13, 'Netflix', 'Estados Unidos', 'Inglês', 'Vince Gilligan', 'https://images6.alphacoders.com/108/1087632.jpg', 'https://www.imdb.com/title/tt0903747/?ref_=fn_al_tt_1', 'https://www.netflix.com/title/70143836', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (11, 'Fleabag', 'Phoebe Waller-Bridge', 'Phoebe Waller-Bridge, Sian Clifford, Olivia Colman, Bill Paterson, Andrew Scott, Ben Aldridge', 'Fleabag, Claire, Godmother, Dad, The Priest, Arsehole Guy', 'Uma comédia dramática sobre a vida de uma jovem mulher tentando lidar com diversas tragédias recentes em sua vida.', 2016, 27, 2, 6, 'Amazon Prime', 'Inglaterra', 'Inglês', 'Phoebe Waller-Bridge', 'https://bleedingcool.com/wp-content/uploads/2019/06/fleabag-1-1200x628.jpg', 'https://www.imdb.com/title/tt5687612/fullcredits/?ref_=tt_ov_st_sm', 'https://www.amazon.com/Fleabag-Season-1/dp/B01J4SSP6E', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (12, 'Dexter', 'James Manos Jr.', 'Michael C. Hall, Jennifer Carpenter, David Zayas', 'Dexter, Debra, Angel Batista', 'De dia, Dexter é um analista de crimes para a polícia de Miami. De noite, ele é um serial killer que busca matar outros assassinos.', 2006, 53, 8, 12, 'Amazon Prime', 'Estados Unidos', 'Inglês', 'Jeff Lindsay, James Manos Jr.', 'https://wallpapercave.com/wp/ALNQZJ7.jpg', 'https://www.imdb.com/title/tt0773262/fullcredits/?ref_=tt_ov_st_sm', 'https://www.primevideo.com/detail/Dexter/0GQGCZ210WB9P5IX51HNSQWZE8', 0);
insert into serie (id, titulo, direcao, elenco, personagens, sinopse, anoLancamento, tempoEpisodio, qntTemporadas, episodiosTemporada, ondeAssistir, paisOrigem, idioma,escritores, linkimagem, linkimdb, linkassistir, contadorfavoritos) values (13, 'The Boys', 'Eric Kripke', 'karl Urban, Jack Quaid, Antony Starr, Erin Moriarty', 'Billy Butcher, Hughie Campbell, Homelander, Annie January', 'Um grupo de vigilantes tenta desbancar diversos super-heróis corruptos e que abusam de seu poder.', 2019, 60, 2, 8, 'Amazon Prime', 'Estados Unidos', 'Inglês', 'Garth Ennis, Darick Robertson.', 'https://hdqwalls.com/wallpapers/the-boys-homelander-4k-hr.jpg', 'https://www.imdb.com/title/tt1190634/fullcredits/?ref_=tt_ov_st_sm', 'https://www.amazon.com/The-Boys-Season-1/dp/B07QNJCXZK', 0);

